// Placeholder univoci per attestati
export const ATTESTATO_PLACEHOLDERS = [
  // Dipendente
  { key: '{{dipendente_nome}}', label: 'Nome dipendente', example: 'Mario' },
  { key: '{{dipendente_cognome}}', label: 'Cognome dipendente', example: 'Rossi' },
  { key: '{{dipendente_codice_fiscale}}', label: 'Codice fiscale dipendente', example: 'RSSMRA80A01H501Z' },
  { key: '{{dipendente_email}}', label: 'Email dipendente', example: 'mario.rossi@email.com' },
  { key: '{{dipendente_telefono}}', label: 'Telefono dipendente', example: '3331112222' },
  { key: '{{ruolo}}', label: 'Ruolo dipendente', example: 'Operaio' },
  // Azienda (unica definizione)
  { key: '{{azienda}}', label: 'Azienda', example: 'Element Srl' },
  { key: '{{azienda_piva}}', label: 'Partita IVA azienda', example: '12345678901' },
  { key: '{{azienda_codice_fiscale}}', label: 'Codice fiscale azienda', example: '12345678901' },
  { key: '{{azienda_sdi}}', label: 'SDI azienda', example: 'ABC1234' },
  { key: '{{azienda_pec}}', label: 'PEC azienda', example: 'element@pec.it' },
  { key: '{{azienda_iban}}', label: 'IBAN azienda', example: 'IT60X0542811101000000123456' },
  { key: '{{azienda_sede}}', label: 'Sede azienda', example: 'Via Roma 1, Milano' },
  { key: '{{azienda_citta}}', label: 'Città azienda', example: 'Milano' },
  { key: '{{azienda_provincia}}', label: 'Provincia azienda', example: 'MI' },
  { key: '{{azienda_cap}}', label: 'CAP azienda', example: '20100' },
  { key: '{{azienda_persona_riferimento}}', label: 'Persona di riferimento azienda', example: 'Luca Bianchi' },
  { key: '{{azienda_mail}}', label: 'Mail azienda', example: 'info@element.it' },
  { key: '{{azienda_telefono}}', label: 'Telefono azienda', example: '0299998888' },
  { key: '{{azienda_note}}', label: 'Note azienda', example: 'Cliente storico' },
  { key: '{{ateco}}', label: 'Ateco', example: '85.59.20' },
  // Formatore
  { key: '{{formatore_nome}}', label: 'Nome formatore', example: 'Giovanni' },
  { key: '{{formatore_cognome}}', label: 'Cognome formatore', example: 'Bianchi' },
  { key: '{{Relatore}}', label: 'Nome completo formatore', example: 'Giovanni Bianchi' },
  { key: '{{formatore_codice_fiscale}}', label: 'Codice fiscale formatore', example: 'BNCGNN80A01H501Z' },
  { key: '{{formatore_email}}', label: 'Email formatore', example: 'giovanni.bianchi@email.com' },
  { key: '{{formatore_telefono}}', label: 'Telefono formatore', example: '3331234567' },
  { key: '{{formatore_specialita}}', label: 'Specialità formatore', example: 'Medicina del lavoro' },
  { key: '{{formatore_indirizzo}}', label: 'Indirizzo residenza formatore', example: 'Via Roma 10' },
  { key: '{{formatore_citta}}', label: 'Città residenza formatore', example: 'Milano' },
  { key: '{{formatore_provincia}}', label: 'Provincia residenza formatore', example: 'MI' },
  { key: '{{formatore_cap}}', label: 'CAP residenza formatore', example: '20100' },
  { key: '{{formatore_data_nascita}}', label: 'Data di nascita formatore', example: '01/01/1980' },
  { key: '{{formatore_luogo_nascita}}', label: 'Luogo di nascita formatore', example: 'Milano' },
  // Co-relatore
  { key: '{{corelatore_nome}}', label: 'Nome co-relatore', example: 'Luca' },
  { key: '{{corelatore_cognome}}', label: 'Cognome co-relatore', example: 'Verdi' },
  { key: '{{corelatore_codice_fiscale}}', label: 'Codice fiscale co-relatore', example: 'VRDLCA80A01H501Z' },
  { key: '{{corelatore_email}}', label: 'Email co-relatore', example: 'luca.verdi@email.com' },
  { key: '{{corelatore_telefono}}', label: 'Telefono co-relatore', example: '3339876543' },
  { key: '{{corelatore_specialita}}', label: 'Specialità co-relatore', example: 'Sicurezza sul lavoro' },
  // Corso
  { key: '{{corso_nome}}', label: 'Nome corso', example: 'Primo Soccorso' },
  { key: '{{Ore corso}}', label: 'Ore corso', example: '8' },
  { key: '{{contenuti}}', label: 'Contenuti', example: 'Primo soccorso, BLS, ...' },
  { key: '{{Normativa}}', label: 'Normativa', example: 'D.Lgs. 81/08' },
  // Date e sessioni
  { key: '{{data_1}}', label: 'Data inizio corso', example: '01/01/2024' },
  { key: '{{data_2}}', label: 'Data fine corso', example: '02/01/2024' },
  { key: '{{data_generazione_template}}', label: 'Data generazione', example: '02/01/2024' },
  { key: '{{sessioni}}', label: 'Elenco sessioni (data, orario inizio/fine)', example: '01/01/2024 09:00-13:00; 02/01/2024 09:00-13:00' },
  { key: '{{sessione_1_data}}', label: 'Data prima sessione', example: '01/01/2024' },
  { key: '{{sessione_1_orario_inizio}}', label: 'Orario inizio prima sessione', example: '09:00' },
  { key: '{{sessione_1_orario_fine}}', label: 'Orario fine prima sessione', example: '13:00' },
  { key: '{{sessione_2_data}}', label: 'Data seconda sessione', example: '02/01/2024' },
  { key: '{{sessione_2_orario_inizio}}', label: 'Orario inizio seconda sessione', example: '09:00' },
  { key: '{{sessione_2_orario_fine}}', label: 'Orario fine seconda sessione', example: '13:00' },
  { key: '{{sessione_3_data}}', label: 'Data terza sessione', example: '03/01/2024' },
  { key: '{{sessione_3_orario_inizio}}', label: 'Orario inizio terza sessione', example: '09:00' },
  { key: '{{sessione_3_orario_fine}}', label: 'Orario fine terza sessione', example: '13:00' },
  { key: '{{sessione_4_data}}', label: 'Data quarta sessione', example: '04/01/2024' },
  { key: '{{sessione_4_orario_inizio}}', label: 'Orario inizio quarta sessione', example: '09:00' },
  { key: '{{sessione_4_orario_fine}}', label: 'Orario fine quarta sessione', example: '13:00' },
  // Altro
  { key: '{{modalita_erogazione}}', label: 'Modalità erogazione', example: 'Presenza' },
  { key: '{{numero_progressivo}}', label: 'Numero progressivo', example: '1' },
  { key: '{{codice_corso}}', label: 'Codice corso', example: 'ABC123' },
  { key: '{{ORE_TOTALI}}', label: 'Ore totali per formatore', example: '8' },
  { key: '{{PRIMA_DATA}}', label: 'Prima data per formatore', example: '01/01/2024' },
  { key: '{{ULTIMA_DATA}}', label: 'Ultima data per formatore', example: '02/01/2024' },
  { key: '{{TARIFFA_ORARIA}}', label: 'Tariffa oraria', example: '50.00' },
  { key: '{{COMPENSO_TOTALE}}', label: 'Compenso totale', example: '400.00' },
  { key: '{{DATA_GENERAZIONE}}', label: 'Data generazione lettera', example: '02/01/2024' },
  { key: '{{NUMERO_PROGRESSIVO}}', label: 'Numero progressivo', example: '1/2024' },
]; 